version: '3'

services:
  api:
    container_name: supervisor
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    entrypoint: wait-for postgres:5432 -t 40  -- ./start.sh
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
