export const SERVER_CONFIG = 'SERVER_CONFIG';
export const TYPEORM_MODULE_CONFIG = 'TYPEORM_MODULE_CONFIG';
export const JWT_MODULE_CONFIG = 'JWT_MODULE_CONFIG';
export const HASH_PROVIDER = 'HASH_PROVIDER';

export const PASSWORD_MIN_LENGTH = 8;

export const USER_NAME_MIN_LENGTH = 3;
export const USER_NAME_MAX_LENGTH = 50;
export const USER_EMAIL_MIN_LENGTH = 5;
export const USER_EMAIL_MAX_LENGTH = 100;