export const PERMISSION_ID_MIN_LENGTH = 5;
export const PERMISSION_ID_MAX_LENGTH = 100;

export const PERMISSION_LABEL_MIN_LENGTH = 5;
export const PERMISSION_LABEL_MAX_LENGTH = 100;

export const IPERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY_INTERFACE';